server:
  port: 8700
spring:
  sleuth:
    enabled: true
    sampler:
      # 请求采样率,配置0.1，即10%
      probability: 1.0
  zipkin:
    # 配置通过HTTP方式发送到Zipkin的地址
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  redis:
    port: 6379
    host: localhost
  application:
    name: api-gateway
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
#          uri: http://localhost:8701
#        - id: api-gateway
#          uri: lb://api-gateway
##          uri: http://localhost:8700
#          predicates:
#            - Path=/gateway/**
#          filters:
#            - StripPrefix=1
        - id: cloud-stream-service
          uri: lb://cloud-stream-service
#          uri: http://localhost:8823
          predicates:
            - Path=/stream/**
          filters:
            - StripPrefix=1
        - id: users
          uri: lb://users
#          uri: http://localhost:8891
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                # 此处的熔断过滤器name，一定要全局唯一
                name: HystrixCommand1
                fallbackUri: forward:/fallbackcontroller
        - id: web-door
          uri: lb://web-door
#          uri: http://localhost:8853
          predicates:
            - Path=/webdoor/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: HystrixCommand
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                # 使用SpEL从容器中获取对象
                #当需要用到这里的对象时需要去filter包下的KeyResolverConfiguration类中开启对应的限流bean
                key-resolver: '#{@pathKeyResolver}'
                # 令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 10
                # 令牌桶的总容量
                redis-rate-limiter.burstCapacity: 10
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  path: /data/logs/{spring.application.name}