## 服务器配置
server:
  port: 8446
## 应用配置
spring:
  application:
    name: authorization-resource
  sleuth:
    enabled: true
    sampler:
      # 请求采样率,配置0.1，即10%
      probability: 1.0
  zipkin:
    # 配置通过HTTP方式发送到Zipkin的地址
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
## 注册中心配置
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 20
    service-url:
      defaultZone: http://localhost:8881/eureka/,http://localhost2:8882/eureka/
